name: documentation

on:
  push:
    branches:    
      - 'main'
  repository_dispatch:

jobs:
  build_docs:
    name: 📚 Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deployment information
        env:
          EVENT: ${{ github.event }}
          AUTHOR: ${{ github.event.client_payload.author }}
          COMMIT: ${{ github.event.client_payload.commit }}
          COMMIT_MSG: ${{ github.event.client_payload.message }}
        run: |
          echo "$AUTHOR deployed https://github.com/$AUTHOR/showdown/commit/$COMMIT with the message: '$COMMIT_MSG'"

      - name: Checkout showdown repo
        uses: actions/checkout@v3
        with:
          repository: bandantonio/showdown
          path: repo
      
      - name: ➕ Copy website artifacts
        id: website
        run: |
          rsync -acvh ./ ./public --exclude README.md --exclude repo --delete
      
      - name: 👷 📚 Build documentation
        id: build_docs
        working-directory: ./repo
        run: |
          docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build
          rsync -acvh ./public/* ../public/
      - name: 🚀 Deploy to GitHub Pages 
        if: steps.build_docs.outcome == 'success'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}