name: documentation

on:
  repository_dispatch:
    types: [ build_docs ]


jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout showdown repo
        uses: actions/checkout@v3
        with:
          repository: bandantonio/showdown
          path: repo
        run: |
          cd repo && ls