name: documentation

on:
  repository_dispatch:
    types: [ build_docs ]

jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ping pong
        id: ping
        run: |
          echo "repository_dispatch triggered - Hello World"